---
image: docker:git
services:
  - docker:dind

stages:
  - compile
  - build_image
  - staging
  - production

variables:
  CONTAINER_RELEASE_IMAGE: "registry.gitlab.com/iflowfor8hours/iflowfor8hours.info/blog"

before_script:
  - UID="$(id -u)"
  - BUILD_DIR="/tmp/build"
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | ssh-add /dev/stdin
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

compile:
  stage: compile
  image: jguyomard/hugo-builder:latest
  script:
    - docker run -v $PWD:/src -it -u $UID:$UID jguyomard/hugo-builder hugo

build_image:
  stage: build_image
  script:
    - docker login -u iflowfor8hours -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

surge:
  stage: surge
  image: node
  script:
    - npm install --global surge
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - dpkg --install hugo_0.31.1_Linux-64bit.deb
    - hugo build -b https://staging.iflowfor8hours.info -d staging
    - surge staging --domain staging.iflowfor8hours.info
    - curl -s -k staging.iflowfor8hours.info| grep matt@iflowfor8hours.info || echo "SOMETHING WENT WRONG"

production:
  stage: production
  variables:
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/iflowfor8hours/iflowfor8hours.info/blog
  image: jguyomard/hugo-builder:latest
  script:
    - hugo --destination "$BUILD_DIR" --baseURL "$BASEURL"
    - minify -r -o $BUILD_DIR/ $BUILD_DIR/
    - rsync --delete -razv -e "ssh" "$BUILD_DIR"/ "$SSH_HOSTDEST" --checksum
