image: docker:git
services:
- docker:dind

stages: 
- staging
- production
- build_image

variables:
	BASEURL: https://iflowfor8hours.info/
	HUGO_BINARY: hugo_0.17_Linux-64bit
	HUGO_VERSION:	0.17
 	CONTAINER_RELEASE_IMAGE: registry.gitlab.com/iflowfor8hours/iflowfor8hours.info/image
	
before_script:
	-	wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz
	-	tar xzf ${HUGO_BINARY}.tar.gz -C ~/bin/
	-	npm install --global surge

staging:
  type: deploy
  script:
	- ~/bin/hugo_0.17_linux_amd64/hugo_0.17_linux_amd64 -b https://staging.iflowfor8hours.info -d staging
	- surge staging --domain staging.iflowfor8hours.info
	- curl -s -k staging.iflowfor8hours.info| grep matt@iflowfor8hours.info || echo "SOMETHING WENT WRONG"

production:
  type: deploy
  script:
	- ~/bin/hugo_0.17_linux_amd64/hugo_0.17_linux_amd64 -b https://iflowfor8hours.info
	- rsync --delete -ravz -e "ssh" ~/clone/public/ www-data@prod.iflowfor8hours.info:/var/www/iflowfor8hours.info
  only:
  - master

build_image:
  stage: build
  script:
  	- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
		- docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

