title = "iflowfor8hours.info"
baseurl = "http://iflowfor8hours.info/"
languageCode = "en-us"
theme = "hugo-hikari-theme"

post = "/:year/:slug"

[params]
  name = "Matt Urbanski"
  description = "devops, automation, webops and explosions."
  copyright = "2015, matt urbanski"

  # Enable comments by entering your Disqus shortname
  # disqusshortname = "spf13"
  # 7b68ee
  # Enable Google Analytics by entering your tracking code
  googleanalytics = ""

  # Links to newer/older blog posts
  newer = "Older"
  older = "Newer"

[params.offcanvas]
  # Menu items
  title = "matt urbanski"
  bio = "systems automation, human, developer"
  followme = "you can find me on the block in addition to"
	# subscribe = "Subscribe"

  [[params.offcanvas.socialnetworks]]
    name = "CV"
    url = "//www.iflowfor8hours.info/MattUrbanski.pdf"
  
  [[params.offcanvas.socialnetworks]]
    name = "Email"
    url = "mailto:matt@iflowfor8hours.info"
  
  [[params.offcanvas.socialnetworks]]
    name = "Github"
    url = "//github.com/iflowfor8hours"

  [[params.offcanvas.socialnetworks]]
    name = "Twitter"
    url = "//twitter.com/iflowfor8hours"

  [[params.offcanvas.socialnetworks]]
    name = "My Presentations"
    url = "//iflowfor8hours.info/presentations.html"
